import{S as I,a as L,i as y}from"./assets/vendor-48b140de.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();var w=new I(".gallery-list a",{captionsData:"alt",captionDelay:250});const E=async t=>{if(t.length===0)return;let r="";document.querySelector(".gallery-list")!=null&&(r=document.querySelector(".gallery-list").innerHTML),r+=await t.map(o=>`
            <li class="gallery-item">
                <a class="gallery-link" href="${o.largeImageURL}">
                    <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
                </a>
                <ul class="item-info">
                    <li><h3 class="item-title">Likes</h3>    <p class="item-text">${o.likes}</p>
                    <li><h3 class="item-title">Views</h3>    <p class="item-text">${o.views}</p>
                    <li><h3 class="item-title">Comments</h3> <p class="item-text">${o.comments}</p>
                    <li><h3 class="item-title">Downloads</h3><p class="item-text">${o.downloads}</p>
                </ul>
            </li>
        `).join(""),gallery.innerHTML=`<ul class="gallery-list">${r}</ul>`,w.refresh()},v=async(t,r,o=15)=>{console.log(`pixabay:search=>[${t}]`);const n="https://pixabay.com/api/",s={key:"43273309-00e3b6b60594751f75d0d2555",q:t,safesearch:!0,image_type:"photo",orientation:"horizontal",per_page:o,page:r};try{const a=n,b={params:s};return await L.get(a,b)}catch(a){throw console.error("pixabay:Error fetching images:",a),a}finally{console.log("pixabay:search.end;")}};let l=1,i="";const x=document.getElementById("searchForm"),c=document.getElementById("searchInput"),g=document.getElementById("submit");g.disabled=!0;const $=document.getElementById("gallery"),p=document.getElementById("loading-indicator"),m=document.getElementById("load-more-btn");c.addEventListener("input",t=>{g.disabled=c.value.trim()===""});x.addEventListener("submit",async t=>{if(t.preventDefault(),$.innerHTML="",h(),i=c.value.trim(),i==="")return console.log("Please enter a search term."),d("Please enter a search term.");c.value="",l=1,await f(l)});m.addEventListener("click",async()=>{l++,await f(l)});async function f(t){h(),console.log("page:",t);try{m.style.display="none";const n=(await v(i,t,15)).data,e=n.hits;E(e);const s=n.totalHits||0;if(console.log("totalHits:",s),s===0){const a=`main: Sorry, there are no images matching your search query: [${i}]. Please try again!`;return u(),d(a)}if(s<=t*15)return B("We're sorry, but you've reached the end of search results.");m.style.display="block"}catch(r){d(r.message)}finally{u()}}function h(){p.style.display="block",m.style.display="none"}function u(){p.style.display="none"}function B(t,r="center"){y.info({title:"Info",message:t,position:r,timeout:1e4})}function d(t,r="center"){y.error({title:"Error",message:t,position:r,timeout:1e4})}
//# sourceMappingURL=commonHelpers.js.map
